### ISSUE TITLE
How did you can use chatGPT API for free? 

### ISSUE THREAD

**Issue by Kingki19** [Kourva/AwesomeChatGPTBot#1]
I have read openAI documentation that you can only build using their API that is not free. Here watch [this](https://openai.com/pricing).

**Comment by Kourva** [comment]
There are many alternative websites that provide access to ChatGPT for free using their API keys. I found one of them and used their APIs.

> When you press F12 on the website and go to the network tab, you can see which API that website uses to respond to your requests. You can use it. I'm not sure if it can be called scraping or not.

*Here is a list of free alternatives to Chat GPT you can explore*: **https://github.com/LiLittleCat/awesome-free-chatgpt**

GoodLuck!
