### ISSUE TITLE
how to use Inline mode?

### ISSUE THREAD

**Issue by chelaxian** [Kourva/AwesomeChatGPTBot#3]
hello Mike!

thank you for such a good free project!
All works like a charm, but can you please instruct me how to use Inline mode with predefined roles?
I activated it in BotFather and when i start messege with tagging bot by its nickname like this @Kourva - telegram just adds text string with suggestion "Ask me", and when I type something - nothing happens. 

can you please write a little guide in github README.md how to use Inline Roles with some examples.

Thank you!

**Comment by Kourva** [comment]
Hi @chelaxian , sorry for late reply. I'm glad you liked it.

You need to write `prompt` after username to get roles (e.g: @chelaxian prompt). if you don't like **prompt**, you can edit `main.py` and change inline handler command in line `191` and add yours like *role*...

```python
191  @bot.inline_handler(lambda query: query.query == "role")
```
