### ISSUE TITLE
/reset command not work

### ISSUE THREAD

**Issue by chelaxian** [Kourva/AwesomeChatGPTBot#31]
when type /reset i get:

```
Dear XXX
You need to start the bot before using it! We need to create an account for you first:
t.me/XXX_bot?start=create
```

is it ok?

**Comment by Kourva** [comment]
Yes it's ok.

You need to start the bot first. `(bot will make you some config files, for api setting and history file)` 
Then you can use /reset to reset (or clear) your history to start new conversation with bot.
