### ISSUE TITLE
Can i use a fakeopen ai as defalt

### ISSUE THREAD

**Issue by Deplyapp** [Kourva/AwesomeChatGPTBot#50]
Can I use face openai ai instead of deepinfra ai as the bot uses deepinfra ai as default

**Comment by Kourva** [comment]
Hi @Deplyapp

Bot has 4 providers, you can edit them in `utils.py` in line **33** in this section:
```python
# Get providers list
PROVIDERS: List[Callable] = [
    deep_infra_chat, # Model: LLAMA-2-70b-Chat-HF
    fstha_chat_gpt,  # Model: ChatGPT-3.5-Turbo
    online_gpt_chat, # Model: ChatGPT-3.5-Turbo
    fakeopen_chat    # Model: ChatGPT-3.5-Turbo
]
```
Then you can remove some or only keep one of them! Bot tries all providers until it gets valid response:
```python
# Try all available providers
for provider in PROVIDERS:
    # Get response from provider
    response: str = provider(history)
```
You can remove this loop and only keep response line with your provider name for example:
```python
# Get response from provider
response: str = fakeopen_chat(history)
```
it could be cool to add panel to bot to handle and set default providers. i will work on it, but for now you can edit these sections to change your provider.

**Comment by Deplyapp** [comment]
Thanks 😊

**Comment by Deplyapp** [comment]
It is possible in the bot to add image Recognition when user sends an image to the bot it Recognize the image and answer the question.

**Comment by Kourva** [comment]
You're welcome.
Yes of course, I may add this feature soon. Maybe using some API or using third-party libraries to recognize text from image.

If you want to do it by yourself, you need to add new message handler to bot to handle only images, then do recognition process and use its result as normal input with chat-GPT functions.

I will add both voice recognition and Image recognition soon.

**Comment by Deplyapp** [comment]
Very good project full support from my side 👍

**Comment by Kourva** [comment]
Thank you very much :smile: :heart:
