### ISSUE TITLE
How can I create an image?

### ISSUE THREAD

**Issue by manizexor-gh** [Kourva/AwesomeChatGPTBot#53]
I had another question, how can I use the ability to generate photos?  In the section about the robot's capabilities, it is mentioned that it can create a photos, but the method of creating them is not mentioned, I wanted to get help

![Screenshot_20240121_203242_Telegraph](https://github.com/Kourva/AwesomeChatGPTBot/assets/71443383/503fa831-a8bc-427c-a89f-2529ca4153f2)

**Comment by Kourva** [comment]
Hi @manizexor-gh 

Those are **upcoming** features. I will add them later in next updates...
