### ISSUE TITLE
Gptbot

### ISSUE THREAD

**Issue by Ihorog** [Kourva/AwesomeChatGPTBot#69]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kourva** [comment]
congratulations! That's 69th issue in this repository...
![300px-Understandable,_Have_a_Great_Day](https://github.com/Kourva/AwesomeChatGPTBot/assets/118578799/fb2a59c9-483f-4a61-93d6-ad7104f2d3a8)
